baseURL = 'https://json-born.github.io/'
languageCode = 'en-us'
title = 'Everything I found out'
theme = 'PaperMod'

[params]
  # Homepage mode - this ensures posts show with proper styling
  mode = "home"

  # Homepage info
  [params.homeInfoParams]
    Title = "Welcome 👋"
    Content = "I’m Dom, aka json-born. Making video games has been my dream since I first sat at a computer. Follow along as I finally get around to chasing it."

  # Show read time and word count
  ShowReadingTime = true
  ShowWordCount = true

  # Show post summary on homepage
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

  # Social icons
  ShowShareButtons = true

  # Social links
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/json-born"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
